### ISSUE TITLE
Use latest version of prompt-toolkit

### ISSUE THREAD

**Issue by oleynikandrey** [httpie/http-prompt#147]
ipython uses prompt-toolkit==2.0.7 which is not compatible with http-prompt==1.0.0, so I can't use both ipython and http-prompt in the same python environment.

    http-prompt 1.0.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.7 which is incompatible.

**Comment by yitzikc** [comment]
As a workaround, I was able to install boarnasia's branch directly:
    pip3 install git+https://github.com/boarnasia/http-prompt@prompt-toolkit-2.0

It still appears to interfere with iPython:
  Attempting uninstall: prompt-toolkit
    Found existing installation: prompt-toolkit 3.0.5
    Uninstalling prompt-toolkit-3.0.5:
      Successfully uninstalled prompt-toolkit-3.0.5

**Comment by BoboTiG** [comment]
Done with 69439599cac3ac243729ebe6be20b3964bb3a4dd.
