### ISSUE TITLE
Support for sending body data that isn't in key:value format

### ISSUE THREAD

**Issue by fogine** [httpie/http-prompt#75]
We should support somehow sending request `body` data as raw string. Without the requirement of providing key=value pair. This is related to jkbrzt/httpie#399 . In the `httpie` library, the issue is solved by command input redirection... Eg.:

``` bash
echo 'some string value' | http POST example.com/person/1
```

Which sort of complicates things for this library... I'm not sure how we should approach this.

**Comment by eliangcs** [comment]
I'm thinking of doing what [xonsh](https://github.com/xonsh/xonsh) does -- we try to parse the command as an HTTP Prompt command first. If it failed, we execute it like a shell command. So users can pipe to httpie or shell anyway they want:

```bash
echo 'some string value' | post example.com/person/1 | grep "abc" | post /upload 
```

This is basically re-implementing a shell in HTTP Prompt.  I guess it won't be hard to do but will require some effort to change the code structure as I did not anticipate this requirement in the beginning of development.

**Comment by fogine** [comment]
> we try to parse the command as an HTTP Prompt command first. If it failed, we execute it like a shell command.

@eliangcs , that would make `http-prompt` quite flexible. I've positive viewpoint on this idea.

> but will require some effort to change the code structure

It'd introduce major changes to `lexer` / `grammar` definitions. I think, it would need quite a lot of work.

**Comment by eliangcs** [comment]
@fogine Sure, I'll start review #74 soon when I have time.

Executing shell commands is easy, but I'm not sure how to deal with the lexer. How do you implement a lexer that is compatible with both shell and HTTP Prompt syntax?

**Comment by fogine** [comment]
> How do you implement a lexer that is compatible with both shell and HTTP Prompt syntax?

@eliangcs , I haven't  fully thought this through yet however currently I think of defining `BashLexer` as fallback when there is no match for any of the main http-prompt lexer definitions (which I think is possible).
Downside of this is that we would basically lose "SyntaxError" highlighting style which would be replaced by bash's `Text` style.  

The same issue described above applies for command execution - that we'll have to execute every invalid command as bash command which can  lead to unexpected behavior (potentially dangerous)... won't we?

**Comment by eliangcs** [comment]
@fogine I think you're right. Executing any invalid command as a bash commandl could be dangerous. Or we can try IPython's approach. IPython uses an exclamation mark to prefix a shell command. So the previous example becomes:

```
!echo 'some string value' | post example.com/person/1 | !grep "abc" | post /upload 
```

**Comment by fogine** [comment]
> IPython uses an exclamation mark to prefix a shell command.

@eliangcs , that is certainly better, I'd rather introduce new command `sh` or `shell` instead of explanation mark which could take `unquoted`, `squoted` or `dquoted` string as an argument... I think that way it would be more transparent...

 The example would become: 

```bash
shell echo 'some string value' | post example.com/person/1 | shell grep "abc" | post /upload 
```

**Comment by fogine** [comment]
So do we give the explanation mark a go, @eliangcs ?
I haven't come with better idea so I'd implement it.

**Comment by eliangcs** [comment]
@fogine yes, feel free to do this 👍

**Comment by gittyup2018** [comment]
Can you add support for <<< ? this works 

HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 252
Content-Type: application/json
Date: Wed, 13 Mar 2019 07:22:56 GMT
Server: nginx

{
    "args": {},
    "data": "raw payload\n",
    "files": {},
    "form": {},
    "headers": {
        "Accept": "application/json, */*",
        "Accept-Encoding": "gzip, deflate",
        "Content-Length": "12",
        "Content-Type": "application/json",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/1.0.2"
    },
    "json": null,
    "url": "https://httpbin.org/post"
}

 http httpbin.org/post <<< 'raw payload'

Credit:

https://github.com/jakubroztocil/httpie/issues/356

henrik242 commented Jan 27, 2017

You can also use http httpbin.org/post <<< 'raw payload'

**Comment by BoboTiG** [comment]
The feature has been merded in HTTPie (`--raw` option, https://github.com/httpie/httpie#182request-data-via---raw). It will be made available for HTTP Prompt for the next HTTPie release (soon).
